### PR TITLE
Add some photo

### PR DESCRIPTION
**Pull request by bugtender**
Add photo include Taipei 101, National Palace Museum, Elephant mountain, Yangmingshan, Ping Hsi, Jiufen and Beitou .

### CODE REVIEW

**Comment by yorkxin** [comment]
Make sure that you put copyright-compatible photos only, because this document will become CC-BY-SA. #7

**Comment by JuanitoFatas** [comment]
If images are from google search, the default is not filtered by license, which is ok I think?

**Comment by bugtender** [comment]
I changed all the photo using CC search on flickr. and add credit message.
http://search.creativecommons.org/

**Comment by JuanitoFatas** [comment]
:clap: :clap: :clap: :clap: :clap: 

Thanks! Merged as da69824. See you in RubyConf :heart:

**Pull request closed without merging**
